In [46]:
import pandas as pd

In [47]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}


df = pd.DataFrame(data)

In [48]:
df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [49]:
df.loc[df["City"].str.contains("New")]
df.loc[df["City"].str.contains("Los")]

    Name         City Department  Salary
1    Bob  Los Angeles         IT   60000
8  Sakib    H Los Ang         HR   70000

In [50]:
df.loc[df["City"].str.contains("new",case= False)]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

In [51]:
df.loc[df["City"].str.contains(r"^Los")]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [ ]:
#ending with.. 
df.loc[df["City"].str.contains("rk$")]

In [ ]:
#start with vowel 

df.loc[df["Name"].str.contains(r"^[AEIOU]")]

In [ ]:
df.loc[df["City"].str.contains(r"New |Los")]

Adding new column

In [ ]:
df = pd.read_csv('student_data (1).csv')
df

In [ ]:
#adding a column with a contrains values 

df['Country'] = 'Bangladesh'
df

In [ ]:
df['Total Marks'] = df['Data Structure Marks'] + df['Algorithm Marks'] + df['Python Marks']
df

In [ ]:
import numpy as np
df['A+ in Ds'] = np.where(df['Data Structure Marks'] > 80, "A+", "A")

df

In [ ]:
#pythn marks ar upore A+ dekhbo 
df["A+ for python"] = np.where(df["Python Marks"] > 80, "A+","A")
df

In [ ]:
df['First Name'] = df["FullName"].str.split(' ').str[0]
df

In [ ]:
#chaile ei noton dataframe ke ekta csv file a stroe kora jay 

df.to_csv('new_dataframe.csv')

Checking duplicate and null values

In [ ]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 70, 95, 90]
}

df = pd.DataFrame(data)
df

In [ ]:
#unique values 

df['Name'].unique()  #eita ekta unique function
len(df['Name'].unique())

In [ ]:
df

In [ ]:
df1 = pd.read_csv('student_data (1).csv')
df1