In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('student_data (1).csv')
print(df)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [3]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [4]:
student_id = df ['StudentID']
print(student_id)
print(type(student_id))

0     PH1001
1     PH1002
2     PH1003
3     PH1004
4     PH1005
5     PH1006
6     PH1007
7     PH1008
8     PH1009
9     PH1010
10    PH1011
11    PH1012
12    PH1013
13    PH1014
14    PH1015
15    PH1016
16    PH1017
17    PH1018
18    PH1019
19    PH1020
Name: StudentID, dtype: object
<class 'pandas.core.series.Series'>

## Different file loading in pandas

In [5]:
csv_file = pd.read_csv('Student_data (1).csv')
print(csv_file)
print(type(csv_file))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka
<class 'pandas.core.frame.DataFrame'>

In [6]:
#excel file 

excel_file =pd.read_excel('phitron_student_marks.xlsx')
print(excel_file)
print(type(excel_file))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka
<class 'pandas.core.frame.DataFrame'>

###   pandas basic functionalites

In [7]:
df = pd.read_csv('student_data (1).csv')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [8]:
#first kicu data nibo 

df.head(10)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet

In [9]:
# last ar dik thke kicu value dekhte chaile 

df.tail(10)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [10]:

col = list(df.columns)
print(col)
print(type(col))

['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks', 'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor', 'Location']
<class 'list'>

In [11]:
import numpy as np 

ind = np.array(df.index)
print(ind)
print(ind.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

In [13]:
df.sample(10)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka

In [14]:
#satistical values 
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

In [15]:
name = df['FullName']
print(name)

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
Name: FullName, dtype: object

Transforming list to datas

In [16]:
#sob gulo ekta data frame ar modde chole asce......

my_list =[["Alice",25], ["Bod",30], ["jhon",22],["Roman",23]]
list_df = pd.DataFrame(my_list,columns=['Name','age'],index=[1,2,3,4])
print(list_df)

    Name  age
1  Alice   25
2    Bod   30
3   jhon   22
4  Roman   23

In [17]:
my_tuple =(("Alice",25), ("Bod",30), ("jhon",22),("Roman",23))
tuple_df = pd.DataFrame(my_tuple,columns=['Name','Age'],index =[1,2,3,4]) 
print(tuple_df)

    Name  Age
1  Alice   25
2    Bod   30
3   jhon   22
4  Roman   23

## Accessing values from dataframe

In [18]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [19]:
Fname = df['FullName']
print(type(Fname))

<class 'pandas.core.series.Series'>

In [20]:
#df.loc[index_start : index_end, col_start:col_end] 
df.loc[10]

StudentID                     PH1011
FullName                Rahim Sheikh
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                    91.0
CompletionStatus         In Progress
EnrollmentDate            2024-06-11
Instructor                 Mr. Karim
Location                      Khulna
Name: 10, dtype: object

In [21]:
#multiple row (normal row) 
df.loc[[3,6,18]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram

In [22]:
#multiple row (range) 

df.loc[3:6]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka

In [ ]:
#single column 
df.loc[:,'Python Marks']
df.loc[:, 'Algorithm Marks']

In [24]:
#Multiple column 
df.loc[:,['EnrollmentDate','Instructor']]

   EnrollmentDate Instructor
0      2024-01-15  Mr. Karim
1      2024-01-20  Ms. Salma
2      2024-02-10  Mr. Karim
3      2024-02-12  Ms. Salma
4      2024-03-05  Mr. Karim
5      2024-03-08  Ms. Salma
6      2024-04-01  Mr. Karim
7      2024-04-22  Ms. Salma
8      2024-05-16  Mr. David
9      2024-05-20  Ms. Salma
10     2024-06-11  Mr. Karim
11     2024-06-14  Ms. Salma
12     2024-07-02  Mr. David
13     2024-07-09  Ms. Salma
14     2024-08-18  Mr. Karim
15     2024-08-21  Ms. Salma
16     2025-09-01  Mr. Karim
17     2025-09-05  Ms. Salma
18     2025-09-15  Mr. David
19     2025-10-02  Ms. Salma

In [25]:
#Row with column 
df.loc [3:7,'CompletionStatus']

3      Completed
4    In Progress
5      Completed
6    In Progress
7      Completed
Name: CompletionStatus, dtype: object

In [26]:
df.loc [3:10,'Location']

3         Sylhet
4     Chattogram
5       Rajshahi
6          Dhaka
7     Chattogram
8          Dhaka
9         Sylhet
10        Khulna
Name: Location, dtype: object

### changing index and column

In [27]:
df_index = df.set_index('StudentID')
df_index

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [28]:
df_index.iloc[:,1:4]

           Data Structure Marks  Algorithm Marks  Python Marks
StudentID
PH1001                     85.0             85.0          88.0
PH1002                     92.0             92.0           NaN
PH1003                     88.0             88.0          85.0
PH1004                     78.0             78.0          82.0
PH1005                      NaN              NaN          95.0
PH1006                     75.0             75.0          78.0
PH1007                     80.0             80.0           NaN
PH1008                     81.0             81.0          85.0
PH1009                     72.0             72.0          76.0
PH1010                     89.0             89.0          88.0
PH1011                      NaN              NaN          91.0
PH1012                     85.0             85.0          87.0
PH1013                     75.0             75.0          79.0
PH1014                      NaN              NaN           NaN
PH1015                     86.0             86.0          84.0
PH1016                     94.0             94.0           NaN
PH1017                     90.0             90.0          93.0
PH1018                     88.0             88.0          85.0
PH1019                      NaN              NaN           NaN
PH1020                     86.0             86.0          89.0

In [29]:
df.rename(columns={'FullName': 'Full Name','Algorithm Marks' : 'Algo marks'},inplace =True)
df

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

## change values and iteration

In [30]:
df

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [31]:
#row deletion 
df.drop(4,inplace =True)

In [32]:
#coulmn delete 

df.drop('Instructor',axis=1,inplace=True)
df

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [39]:
df.loc[1,'Python Marks'] = 85
df.head()

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,85.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,90.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,87.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi

In [38]:
df.loc[1,'CompletionStatus'] = 'Completed'
df.head()

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,90.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,90.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,87.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi

In [41]:
df.loc[1:3,'Python Marks'] += 2 
df.head()

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,89.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,94.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,91.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi

In [42]:
df

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,89.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,94.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,91.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [43]:
for i,series in df.iterrows(): 
    print(f"{i} : {series}")

0 : StudentID                    PH1001
Full Name               Alif Rahman
Data Structure Marks           85.0
Algo marks                     85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Location                      Dhaka
Name: 0, dtype: object
1 : StudentID                      PH1002
Full Name               Fatima Akhter
Data Structure Marks             92.0
Algo marks                       92.0
Python Marks                     89.0
CompletionStatus            Completed
EnrollmentDate             2024-01-20
Location                   Chattogram
Name: 1, dtype: object
2 : StudentID                      PH1003
Full Name               Imran Hossain
Data Structure Marks             88.0
Algo marks                       88.0
Python Marks                     94.0
CompletionStatus            Completed
EnrollmentDate             2024-02-10
Location                        Dhaka
Name: 2, dtype: object
3 : StudentID                         PH1004
Full Name               Jannatul Ferdous
Data Structure Marks                78.0
Algo marks                          78.0
Python Marks                        91.0
CompletionStatus               Completed
EnrollmentDate                2024-02-12
Location                          Sylhet
Name: 3, dtype: object
5 : StudentID                    PH1006
Full Name               Laila Begum
Data Structure Marks           75.0
Algo marks                     75.0
Python Marks                   78.0
CompletionStatus          Completed
EnrollmentDate           2024-03-08
Location                   Rajshahi
Name: 5, dtype: object
6 : StudentID                       PH1007
Full Name               Mahmudul Hasan
Data Structure Marks              80.0
Algo marks                        80.0
Python Marks                       NaN
CompletionStatus           In Progress
EnrollmentDate              2024-04-01
Location                         Dhaka
Name: 6, dtype: object
7 : StudentID                    PH1008
Full Name               Nadia Islam
Data Structure Marks           81.0
Algo marks                     81.0
Python Marks                   85.0
CompletionStatus          Completed
EnrollmentDate           2024-04-22
Location                 Chattogram
Name: 7, dtype: object
8 : StudentID                   PH1009
Full Name               Omar Faruq
Data Structure Marks          72.0
Algo marks                    72.0
Python Marks                  76.0
CompletionStatus         Completed
EnrollmentDate          2024-05-16
Location                     Dhaka
Name: 8, dtype: object
9 : StudentID                     PH1010
Full Name               Priya Sharma
Data Structure Marks            89.0
Algo marks                      89.0
Python Marks                    88.0
CompletionStatus           Completed
EnrollmentDate            2024-05-20
Location                      Sylhet
Name: 9, dtype: object
10 : StudentID                     PH1011
Full Name               Rahim Sheikh
Data Structure Marks             NaN
Algo marks                       NaN
Python Marks                    91.0
CompletionStatus         In Progress
EnrollmentDate            2024-06-11
Location                      Khulna
Name: 10, dtype: object
11 : StudentID                        PH1012
Full Name               Sadia Chowdhury
Data Structure Marks               85.0
Algo marks                         85.0
Python Marks                       87.0
CompletionStatus              Completed
EnrollmentDate               2024-06-14
Location                     Chattogram
Name: 11, dtype: object
12 : StudentID                     PH1013
Full Name               Tanvir Ahmed
Data Structure Marks            75.0
Algo marks                      75.0
Python Marks                    79.0
CompletionStatus           Completed
EnrollmentDate            2024-07-02
Location                       Dhaka
Name: 12, dtype: object
13 : StudentID                    PH1014
Full Name                Urmi Akter
Data Structure Marks            NaN
Algo marks                      NaN
Python Marks                    NaN
CompletionStatus        Not Started
EnrollmentDate           2024-07-09
Location                   Rajshahi
Name: 13, dtype: object
14 : StudentID                     PH1015
Full Name               Wahiduzzaman
Data Structure Marks            86.0
Algo marks                      86.0
Python Marks                    84.0
CompletionStatus           Completed
EnrollmentDate            2024-08-18
Location                       Dhaka
Name: 14, dtype: object
15 : StudentID                     PH1016
Full Name               Ziaur Rahman
Data Structure Marks            94.0
Algo marks                      94.0
Python Marks                     NaN
CompletionStatus         In Progress
EnrollmentDate            2024-08-21
Location                  Chattogram
Name: 15, dtype: object
16 : StudentID                    PH1017
Full Name               Afsana Mimi
Data Structure Marks           90.0
Algo marks                     90.0
Python Marks                   93.0
CompletionStatus          Completed
EnrollmentDate           2025-09-01
Location                      Dhaka
Name: 16, dtype: object
17 : StudentID                    PH1018
Full Name               Babul Ahmed
Data Structure Marks           88.0
Algo marks                     88.0
Python Marks                   85.0
CompletionStatus          Completed
EnrollmentDate           2025-09-05
Location                     Sylhet
Name: 17, dtype: object
18 : StudentID                     PH1019
Full Name               Faria Rahman
Data Structure Marks             NaN
Algo marks                       NaN
Python Marks                     NaN
CompletionStatus         Not Started
EnrollmentDate            2025-09-15
Location                  Chattogram
Name: 18, dtype: object
19 : StudentID                   PH1020
Full Name               Nasir Khan
Data Structure Marks          86.0
Algo marks                    86.0
Python Marks                  89.0
CompletionStatus         Completed
EnrollmentDate          2025-10-02
Location                     Dhaka
Name: 19, dtype: object

In [44]:
for i in df.itertuples(): 
    print(i)

Pandas(Index=0, StudentID='PH1001', _2='Alif Rahman', _3=85.0, _4=85.0, _5=88.0, CompletionStatus='Completed', EnrollmentDate='2024-01-15', Location='Dhaka')
Pandas(Index=1, StudentID='PH1002', _2='Fatima Akhter', _3=92.0, _4=92.0, _5=89.0, CompletionStatus='Completed', EnrollmentDate='2024-01-20', Location='Chattogram')
Pandas(Index=2, StudentID='PH1003', _2='Imran Hossain', _3=88.0, _4=88.0, _5=94.0, CompletionStatus='Completed', EnrollmentDate='2024-02-10', Location='Dhaka')
Pandas(Index=3, StudentID='PH1004', _2='Jannatul Ferdous', _3=78.0, _4=78.0, _5=91.0, CompletionStatus='Completed', EnrollmentDate='2024-02-12', Location='Sylhet')
Pandas(Index=5, StudentID='PH1006', _2='Laila Begum', _3=75.0, _4=75.0, _5=78.0, CompletionStatus='Completed', EnrollmentDate='2024-03-08', Location='Rajshahi')
Pandas(Index=6, StudentID='PH1007', _2='Mahmudul Hasan', _3=80.0, _4=80.0, _5=nan, CompletionStatus='In Progress', EnrollmentDate='2024-04-01', Location='Dhaka')
Pandas(Index=7, StudentID='PH1008', _2='Nadia Islam', _3=81.0, _4=81.0, _5=85.0, CompletionStatus='Completed', EnrollmentDate='2024-04-22', Location='Chattogram')
Pandas(Index=8, StudentID='PH1009', _2='Omar Faruq', _3=72.0, _4=72.0, _5=76.0, CompletionStatus='Completed', EnrollmentDate='2024-05-16', Location='Dhaka')
Pandas(Index=9, StudentID='PH1010', _2='Priya Sharma', _3=89.0, _4=89.0, _5=88.0, CompletionStatus='Completed', EnrollmentDate='2024-05-20', Location='Sylhet')
Pandas(Index=10, StudentID='PH1011', _2='Rahim Sheikh', _3=nan, _4=nan, _5=91.0, CompletionStatus='In Progress', EnrollmentDate='2024-06-11', Location='Khulna')
Pandas(Index=11, StudentID='PH1012', _2='Sadia Chowdhury', _3=85.0, _4=85.0, _5=87.0, CompletionStatus='Completed', EnrollmentDate='2024-06-14', Location='Chattogram')
Pandas(Index=12, StudentID='PH1013', _2='Tanvir Ahmed', _3=75.0, _4=75.0, _5=79.0, CompletionStatus='Completed', EnrollmentDate='2024-07-02', Location='Dhaka')
Pandas(Index=13, StudentID='PH1014', _2='Urmi Akter', _3=nan, _4=nan, _5=nan, CompletionStatus='Not Started', EnrollmentDate='2024-07-09', Location='Rajshahi')
Pandas(Index=14, StudentID='PH1015', _2='Wahiduzzaman', _3=86.0, _4=86.0, _5=84.0, CompletionStatus='Completed', EnrollmentDate='2024-08-18', Location='Dhaka')
Pandas(Index=15, StudentID='PH1016', _2='Ziaur Rahman', _3=94.0, _4=94.0, _5=nan, CompletionStatus='In Progress', EnrollmentDate='2024-08-21', Location='Chattogram')
Pandas(Index=16, StudentID='PH1017', _2='Afsana Mimi', _3=90.0, _4=90.0, _5=93.0, CompletionStatus='Completed', EnrollmentDate='2025-09-01', Location='Dhaka')
Pandas(Index=17, StudentID='PH1018', _2='Babul Ahmed', _3=88.0, _4=88.0, _5=85.0, CompletionStatus='Completed', EnrollmentDate='2025-09-05', Location='Sylhet')
Pandas(Index=18, StudentID='PH1019', _2='Faria Rahman', _3=nan, _4=nan, _5=nan, CompletionStatus='Not Started', EnrollmentDate='2025-09-15', Location='Chattogram')
Pandas(Index=19, StudentID='PH1020', _2='Nasir Khan', _3=86.0, _4=86.0, _5=89.0, CompletionStatus='Completed', EnrollmentDate='2025-10-02', Location='Dhaka')

### sorting

In [45]:
df

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,89.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,94.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,91.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [47]:
# eita by default choto thke boro asbe.... 
copy = df.sort_values('Data Structure Marks')
copy

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Location
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,91.0,Completed,2024-02-12,Sylhet
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,94.0,Completed,2024-02-10,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,89.0,Completed,2024-01-20,Chattogram
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [51]:
# jdi boro thke choto chai 
copy = df.sort_values(['Data Structure Marks','Algo marks'],ascending = False)
copy

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
1,PH1002,Fatima Akhter,92.0,92.0,89.0,Completed,2024-01-20,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,94.0,Completed,2024-02-10,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,91.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [52]:
not_started = df.loc[df['CompletionStatus'] == 'Not Started	']
not_started

Empty DataFrame
Columns: [StudentID, Full Name, Data Structure Marks, Algo marks, Python Marks, CompletionStatus, EnrollmentDate, Location]
Index: []

In [53]:
df

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,89.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,94.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,91.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [55]:
not_started = df.loc[df['CompletionStatus'] =='Not Started']
not_started

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Location
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [56]:
started = df.loc[df['CompletionStatus'] =='Completed']
started

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,89.0,Completed,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,94.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,91.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [60]:
completed_ds = df.loc[(df['CompletionStatus'] =='Completed') & (df['Data Structure Marks']>= 90) & (df['Python Marks'] >= 80)]
completed_ds

,StudentID,Full Name,Data Structure Marks,Algo marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,89.0,Completed,2024-01-20,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka